apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  annotations:
    fluxcd.io/automated: "true"
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: maintenance
        image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 80
