apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: maintenance 
  annotations:
    fluxcd.io/automated: "true"
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: maintenance
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 021155830612.dkr.ecr.us-east-1.amazonaws.com/nginx-proxy:58fdf78facaca788a090166f90aa825eb816c996
        ports:
        - containerPort: 80
