name: Docker Image CI

on:
  push:
    paths:
    - Docker*
    - docker*
    - html/**
    branches: [ main ]
  pull_request:
    paths:
    - Docker*
    - docker*
    - html/**

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: nginx-proxy:${{ github.sha }}
  AWS_ECR_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup ECR
      run: |
        # Login to AWS ECR
        #$( aws ecr get-login --no-include-email )
        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login \
              --username AWS \
              --password-stdin ${AWS_ECR_URL}
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t ${AWS_ECR_URL}/${CONTAINER_IMAGE} .
    # Only push to registry on main
    - name: Push
      if: github.ref == 'refs/heads/main'
      run: |
        # Push image to AWS ECR
        docker push ${AWS_ECR_URL}/${CONTAINER_IMAGE}
    - name: CleanUP
      run: |
        find /home/runner
        echo "Cleaning up some stuff"
        rm -rf /home/runner/.docker/config.json
