name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        TAG=$(date +%s)
        echo "Building with tag: ${TAG}"
        docker build --tag nginx-proxy:${TAG} .
        echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
        echo "Pushing with tag: ${TAG}"
        docker push nginx-proxy:${TAG}
